#print("Hello World!")
#print("Hello again")
#print("This is fun.")
#print('Yay, Printing!')
#print("I'd much rather you 'not'.")
#print("I like typing this.")
#print('I "said" do not touch this.')
print("I love my dogs.")